TK_SION/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView
import login.urls as login
import profil_user.urls as profil_user
import registrasi.urls as registrasi
import profil_organisasi.urls as profil_organisasi

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include(login,namespace='login')),
    url(r'^profile/',include(profil_user,namespace='profil_user')),
    url(r'^register/',include(registrasi,namespace='register')),
	url(r'^profil_organisasi/',include(profil_organisasi,namespace='profil_organisasi')),
]

login/urls.py
from django.conf.urls import url
from .views import index, login
from .custom_auth import auth_login, auth_logout

urlpatterns = [
    url(r'^$',index,name='index'),
    url(r'^login/$',login,name='login'),
    url(r'^custom_auth/login/$',auth_login,name='auth_login'),
    url(r'^custom_auth/logout/$',auth_logout,name='auth_logout'),
]

registrasi/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^pilih_role/$',index,name='index'),
    url(r'^$',register_page,name='regis'),
    url(r'^insert_regis',konfirmasi_registrasi,name='konfirmasi'),
    url(r'^insert_organisasi',konfirmasi_registrasi_org,name='konfirmasi_org'),
    url(r'^data_organisasi',halaman_habis_regis_org,name='abis_org'),
]

registrasi/models.py
from django.db import models

# Create your models here.

registrasi/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from login.db_helper import KoneksiDb
from django.contrib import messages

# Create your views here.
response = {}

def index(request):
    if 'email' in request.session :
        print('logged in')
        response['login'] = True
        return HttpResponseRedirect(reverse('profil_user:index'))
    else :
        print('mau regis')
        response['login'] = False
        html = 'pilih_role.html'
        return render(request, html, response)

def register_page(request):
    if 'email' in request.session :
        print('logged in')
        response['login'] = True
        return render(request,'styleguide.html',response)
    else:
        if request.method == "POST":
            role = request.POST.get('role_user')
            request.session['role'] = role
            if role == 'Donatur':
                html = 'register_donatur.html'
                return render(request, html, response)
            if role == 'Relawan':
                html = 'register_relawan.html'
                return render(request, html, response)
            if role == 'Sponsor':
                html = 'register_sponsor.html'
                return render(request, html, response)
            if role == 'Pengurus Organisasi':
                html = 'register_organisasi.html'
                return render(request, html, response)

def konfirmasi_registrasi(request):
    if request.method == "POST":
        role = request.session['role']
        email = request.POST.get('email')
        password = request.POST.get('password')
        nama = request.POST.get('nama')
        kecamatan = request.POST.get('kecamatan')
        kabupaten = request.POST.get('kabupaten')
        provinsi = request.POST.get('propinsi')
        kode_pos = request.POST.get('kode_pos')
        jalan_no_rumah = request.POST.get('jalan')
        alamat_lengkap = "{}".format(kecamatan) + ", " + "{}".format(kabupaten) + ", " + "{}".format(provinsi) + ", " + "{}".format(jalan_no_rumah) + ". Kode Pos: " + "{}".format(kode_pos)
        conn = KoneksiDb()

        if role.lower() == 'donatur':
            conn.insert_regis_user(role, email, password, nama, alamat_lengkap, '', '', '', '')
        elif role.lower() == 'sponsor':
            logo = request.POST.get('logo')
            conn.insert_regis_user(role, email, password, nama, alamat_lengkap, '', '', '', logo)
        else:
            tanggal_lahir = request.POST.get('tanggal_lahir')
            nomor_handphone = request.POST.get('nomor_handphone')
            keahlian = request.POST.get('keahlian')
            conn.insert_regis_user(role, email, password, nama, alamat_lengkap, tanggal_lahir, nomor_handphone, keahlian, '')


        messages.info(request, 'Registrasi success')
        request.session['email'] = email
        request.session['password'] = password
        request.session['role'] = role.lower()
        response['role'] = role.lower()
        response['login'] = True
        return HttpResponseRedirect(reverse('profil_user:index'))
    return HttpResponseRedirect(reverse('login:index'))

def konfirmasi_registrasi_org(request):
    if request.method == "POST":
        email = request.POST.get('email')
        website = request.POST.get('website')
        nama = request.POST.get('nama')
        provinsi = request.POST.get('provinsi')
        kabupaten_kota = request.POST.get('kabupaten_kota')
        kecamatan = request.POST.get('kecamatan')
        kelurahan = request.POST.get('kelurahan')
        kode_pos = request.POST.get('kode_pos')
        nama_pengurus = request.POST.get('nama_pengurus')
        email_pengurus = request.POST.get('email_pengurus')
        alamat_pengurus = request.POST.get('alamat_pengurus')
        alamat_lengkap = "{}".format(kecamatan) + ", " + "{}".format(kabupaten_kota) + ", " + "{}".format(provinsi) + ", " + "{}".format(kelurahan) + ". Kode Pos: " + "{}".format(kode_pos)
        conn = KoneksiDb()

        conn.insert_regis_organisasi(email, website, nama, provinsi, kabupaten_kota, kecamatan, kelurahan, kode_pos, nama_pengurus, email_pengurus, alamat_pengurus)
        conn.cursor.execute("INSERT INTO organisasi VALUES(%s,%s,%s,%s,%s,%s,%s,%s,%s)",[email,website,nama,provinsi,kabupaten_kota,kecamatan,kelurahan,kode_pos,'True'])
        response['email'] = email
        response['website'] = website
        response['nama'] = nama
        response['alamat_lengkap'] = alamat_lengkap
        response['nama_pengurus'] = nama_pengurus
        response['email_pengurus'] = email_pengurus
        response['alamat_pengurus'] = alamat_pengurus
        conn.cursor.execute("select count(*) from sion.organisasi_terverifikasi")
        jumlah = conn.cursor.fetchone()[0]
        response['password'] = 'ABC'+ str(jumlah+1)
        response['no_registrasi'] = 'REG0'+str(jumlah+1)
        return HttpResponseRedirect(reverse('register:abis_org'))

def halaman_habis_regis_org(request):
    html = 'org_abis_regis.html'
    return render(request, html, response)

registrasi/templates/org_abis_regis.html
{% load staticfiles %}
{% load static %}

<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css">
  <link rel="stylesheet" href="{% static 'theme.css'%}" type="text/css"> </head>

<body class="bg-secondary">
  <nav class="navbar navbar-expand-md bg-secondary navbar-dark">
    <a class="navbar-brand" href="#">
      <i class="fa d-inline fa-lg fa-cloud"></i>
      <b> SION</b>
    </a>
    <div class="container">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <form class="form-inline m-0">
          <input class="form-control mr-2" type="text" placeholder="Search">
          <button class="btn btn-success" type="submit">Search</button>
        </form>
      </div>
    </div>
    <a class="btn navbar-btn ml-2 text-white btn-secondary" href="login/">
      <i class="fa d-inline fa-lg fa-user-circle-o"></i> Sign in/Register</a>
  </nav>
  <div class="py-5 text-white bg-secondary">
    <div class="container">
      <div class="row">
        <div class="col-md-12 text-center">
          <h1 class="text-center">
            <b>Anda berhasil mendaftar!</b>
          </h1>
          <div class="col-md-12">
            <ul class="">
              <li>
                <b>Nomor registrasi organisasi:</b>
                <br>{{ no_registrasi }}</li>
              <li>
                <b>Email pengurus:</b>
                <br>{{ email_pengurus }}</li>
              <li>
                <b>Password pengurus:</b>
                <br>{{ password }}</li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  <pingendo onclick="window.open('https://pingendo.com/', '_blank')" style="cursor:pointer;position: fixed;bottom: 10px;right:10px;padding:4px;background-color: #00b0eb;border-radius: 8px; width:250px;display:flex;flex-direction:row;align-items:center;justify-content:center;font-size:14px;color:white">Made with Pingendo Free&nbsp;&nbsp;
    <img src="https://pingendo.com/site-assets/Pingendo_logo_big.png" class="d-block" alt="Pingendo logo" height="16">
  </pingendo>
</body>

</html>

registrasi/templates/pilih_role.html
{% load staticfiles %}
{% load static %}

<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css">
  <link rel="stylesheet" href="{% static 'theme.css'%}" type="text/css">
</head>

<body class="bg-secondary">
  <nav class="navbar navbar-expand-md bg-secondary navbar-dark">
    <a class="navbar-brand" href="#">
      <i class="fa d-inline fa-lg fa-cloud"></i>
      <b> SION</b>
    </a>
    <div class="container">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto"></ul>
        <form class="form-inline m-0">
          <input class="form-control mr-2" type="text" placeholder="Search">
          <button class="btn btn-success" type="submit">Search</button>
        </form>
      </div>
    </div>
    <a class="btn navbar-btn ml-2 text-white btn-secondary">
      <i class="fa d-inline fa-lg fa-user-circle-o"></i> Sign in/Register</a>
  </nav>
  <div class="py-5">
    <div class="container">
      <div class="row">
        <div class="col-md-3"> </div>
        <div class="col-md-6">
          <div class="card text-white p-5 bg-secondary">
            <div class="card-body">
              <h1 class="mb-4">Register: Pilih Role </h1>
              <form action="{% url 'register:regis' %}" method="POST">
                {% csrf_token %}
                <select name="role_user">
                    <option value="Donatur">Donatur</option>
                    <option value="Relawan">Relawan</option>
                    <option value="Sponsor">Sponsor</option>
                    <option value="Pengurus Organisasi">Pengurus Organisasi</option>
                </select>
                <button type="submit" class="btn btn-success">Pilih Role</button>
              </form>
            </div>
        </div>
      </div>
    </div>
  </div>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  <pingendo onclick="window.open('https://pingendo.com/', '_blank')" style="cursor:pointer;position: fixed;bottom: 10px;right:10px;padding:4px;background-color: #00b0eb;border-radius: 8px; width:250px;display:flex;flex-direction:row;align-items:center;justify-content:center;font-size:14px;color:white">Made with Pingendo Free&nbsp;&nbsp;
    <img src="https://pingendo.com/site-assets/Pingendo_logo_big.png" class="d-block" alt="Pingendo logo" height="16">
  </pingendo>
</body>

</html>

registrasi/templates/register_donatur.html
{% load staticfiles %}
{% load static %}

<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css">
  <link rel="stylesheet" href="{% static 'theme.css'%}" type="text/css">
</head>

<body class="bg-secondary">
  <div class ="container">
      {% for message in messages %}
      <div class="alert {{ message.tags }} alert-dismissible" role="alert" id="django-messages">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close" style="margin-right: 15px;">
          <span aria-hidden="true">&times;</span>
        </button>
        {{ message }}
      </div>
      {% endfor %}
    </div>      
  <nav class="navbar navbar-expand-md bg-secondary navbar-dark">
    <a class="navbar-brand" href="0, Homepage.html">
      <i class="fa d-inline fa-lg fa-cloud"></i>
      <b> SION</b>
    </a>
    <div class="container">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto"></ul>
        <form class="form-inline m-0">
          <input class="form-control mr-2" type="text" placeholder="Search">
          <button class="btn btn-success" type="submit">Search</button>
        </form>
      </div>
    </div>
    <a class="btn navbar-btn ml-2 text-white btn-secondary">
      <i class="fa d-inline fa-lg fa-user-circle-o"></i> Sign in/Register</a>
  </nav>
  <div class="py-5 text-center filter-dark" style="background-image: url('Charity.jpg');background-position:left top;background-size:cover;">
    <div class="container py-5">
      <div class="row">
        <div class="col-md-12">
          <h1 class="display-3 mb-4 text-light text-left">
            <b>Pendaftaran Sebagai Donatur</b>
          </h1>
          <p class="lead mb-5 text-left">Belum mempunyai akun? Daftarlah bersama kami di SION.</p>
        </div>
      </div>
    </div>
  </div>
  <div class="py-3 bg-secondary">
    <div class="container">
      <div class="row">
        <div class="col-md-11">
          <form action="{% url 'register:konfirmasi' %}" method="POST">
            {% csrf_token %}
            <div class="form-group">
              <label>Nama</label>
              <input type="text" name = "nama" class="form-control" placeholder="Nama" required> </div>
            <div class="form-group">
              <label>Email</label>
              <input type="email" name = "email" class="form-control" placeholder="Email" required> </div>
            <div class="form-group">
              <label>Password</label>
              <input type="password" name = "password" class="form-control" placeholder="Password" required> </div>
            <div class="form-group">
              <label>Kecamatan</label>
              <input type="text" name = "kecamatan" class="form-control" placeholder="Kecamatan" required> </div>
            <div class="form-group">
              <label>Kabupaten</label>
              <input type="text" name = "kabupaten" class="form-control" placeholder="Kabupaten" required> </div>
            <div class="form-group">
              <label>Provinsi</label>
              <input type="text" name "propinsi" class="form-control" placeholder="Provinsi" required> </div>
            <div class="form-group">
              <label>Kode Pos</label>
              <input type="text" name = "kode_pos" class="form-control" placeholder="Kode Pos" required> </div>
            <div class="form-group">
              <label>Jalan/Desa/Kelurahan/No.Rumah</label>
              <input type="text" name = "jalan" class="form-control" placeholder="Kode Pos
Jalan/Desa/Kelurahan/No.Rumah" required> </div>
            <button type="submit" class="btn btn-success">Submit</button>
          </form>
        </div>
      </div>
    </div>
  </div>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  <pingendo onclick="window.open('https://pingendo.com/', '_blank')" style="cursor:pointer;position: fixed;bottom: 10px;right:10px;padding:4px;background-color: #00b0eb;border-radius: 8px; width:250px;display:flex;flex-direction:row;align-items:center;justify-content:center;font-size:14px;color:white">Made with Pingendo Free&nbsp;&nbsp;
    <img src="https://pingendo.com/site-assets/Pingendo_logo_big.png" class="d-block" alt="Pingendo logo" height="16">
  </pingendo>
</body>

</html>

registrasi/templates/register_organisasi.html
{% load staticfiles %}
{% load static %}

<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css">
  <link rel="stylesheet" href="{% static 'theme.css'%}" type="text/css">
</head>

<body class="bg-secondary">
  <div class ="container">
      {% for message in messages %}
      <div class="alert {{ message.tags }} alert-dismissible" role="alert" id="django-messages">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close" style="margin-right: 15px;">
          <span aria-hidden="true">&times;</span>
        </button>
        {{ message }}
      </div>
      {% endfor %}
    </div>

  <nav class="navbar navbar-expand-md bg-secondary navbar-dark">
    <a class="navbar-brand" href="#">
      <i class="fa d-inline fa-lg fa-cloud"></i>
      <b> SION</b>
    </a>
    <div class="container">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto"></ul>
        <form class="form-inline m-0">
          <input class="form-control mr-2" type="text" placeholder="Search">
          <button class="btn btn-success" type="submit">Search</button>
        </form>
      </div>
    </div>
    <a class="btn navbar-btn ml-2 text-white btn-secondary">
      <i class="fa d-inline fa-lg fa-user-circle-o"></i> Sign in/Register</a>
  </nav>
  <div class="py-5 text-center filter-dark" style="background-image: url('Charity.jpg');background-position:left top;background-size:cover;">
    <div class="container py-5">
      <div class="row">
        <div class="col-md-12">
          <h1 class="display-3 mb-4 text-light text-left">
            <b>Pendaftaran Organisasi</b>
          </h1>
          <p class="lead mb-5 text-left">Belum mempunyai akun? Daftarlah bersama kami di SION.</p>
        </div>
      </div>
    </div>
  </div>
  <div class="bg-secondary">
    <div class="container">
      <div class="row text-center bg-light">
        <div class="border-dark px-5 bg-secondary w-50">
          <div class="btn-group">
            <button class="btn dropdown-toggle btn-secondary" data-toggle="dropdown"> User</button>
            <div class="dropdown-menu">
              <a class="dropdown-item" href="2.1, Registrasi Relawan.html">Relawan
                <br> </a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="2.2, Registrasi Donatur.html">Donatur</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="2.3, Registrasi Sponsor.html">Sponsor</a>
            </div>
          </div>
        </div>
        <div class="px-5 border-dark bg-light">
          <a href="#" class="btn btn-lg btn-light w-50">Organisasi dan Pengurus Organisasi</a>
        </div>
      </div>
    </div>
  </div>
  <div class="py-3 bg-secondary">
    <div class="container">
      <div class="row">
        <div class="col-md-11">
          <form action="{% url 'register:konfirmasi_org' %}" method="POST">
            {% csrf_token %}
            <div class="form-group">
              <label>Nama Organisasi</label>
              <input type="text" name="nama" class="form-control" placeholder="Nama Organisasi" required> </div>
            <div class="form-group">
              <label>Website</label>
              <input type="text" name="website" class="form-control" placeholder="Website" required> </div>
            <div class="form-group">
              <label>Email</label>
              <input type="email" name="email" class="form-control" placeholder="Email" required> </div>
            <div class="form-group">
              <label>Kecamatan</label>
              <input type="text" name="kecamatan" class="form-control" placeholder="Kecamatan" required> </div>
            <div class="form-group">
              <label>Kabupaten</label>
              <input type="text" name="kabupaten_kota" class="form-control" placeholder="Kabupaten" required> </div>
            <div class="form-group">
              <label>Provinsi</label>
              <input type="text" name="provinsi" class="form-control" placeholder="Provinsi" required> </div>
            <div class="form-group">
              <label>Jalan/Desa/Kelurahan/No.Rumah</label>
              <input type="text" name="kelurahan" class="form-control" placeholder="Jalan/Desa/Kelurahan/No.Rumah" required> </div>
            <div class="form-group">
              <label>Kode Pos</label>
              <input type="text" name="kode_pos" class="form-control" placeholder="Kode Pos" required> </div>
            <div class="form-group">
              <label>Nama Pengurus</label>
              <input type="text" name="nama_pengurus" class="form-control" placeholder="Nama Pengurus" required> </div>
            <div class="form-group">
              <label>Email Pengurus</label>
              <input type="email" name="email_pengurus" class="form-control" placeholder="Email Pengurus" required> </div>
            <div class="form-group">
              <label>Alamat Pengurus</label>
              <input type="text" name="alamat_pengurus" class="form-control" placeholder="Alamat Pengurus" required> </div>
            <button type="submit" class="btn btn-success">Submit</button>
          </form>
        </div>
      </div>
    </div>
  </div>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  <pingendo onclick="window.open('https://pingendo.com/', '_blank')" style="cursor:pointer;position: fixed;bottom: 10px;right:10px;padding:4px;background-color: #00b0eb;border-radius: 8px; width:250px;display:flex;flex-direction:row;align-items:center;justify-content:center;font-size:14px;color:white">Made with Pingendo Free&nbsp;&nbsp;
    <img src="https://pingendo.com/site-assets/Pingendo_logo_big.png" class="d-block" alt="Pingendo logo" height="16">
  </pingendo>
</body>

</html>