TK_SION/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView
import login.urls as login
import profil_user.urls as profil_user
import registrasi.urls as registrasi
import profil_organisasi.urls as profil_organisasi

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include(login,namespace='login')),
    url(r'^profile/',include(profil_user,namespace='profil_user')),
    url(r'^register/',include(registrasi,namespace='register')),
	url(r'^profil_organisasi/',include(profil_organisasi,namespace='profil_organisasi')),
]

login/urls.py
from django.conf.urls import url
from .views import index, login
from .custom_auth import auth_login, auth_logout

urlpatterns = [
    url(r'^$',index,name='index'),
    url(r'^login/$',login,name='login'),
    url(r'^custom_auth/login/$',auth_login,name='auth_login'),
    url(r'^custom_auth/logout/$',auth_logout,name='auth_logout'),
]

login/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from __future__ import unicode_literals

from django.db import models


class Berita(models.Model):
    kode_unik = models.CharField(primary_key=True, max_length=50)
    kegiatan = models.ForeignKey('Kegiatan', models.DO_NOTHING, db_column='kegiatan')
    judul = models.CharField(max_length=100)
    deskripsi = models.TextField()
    tgl_update = models.DateField()
    tgl_kegiatan = models.DateField()

    class Meta:
        managed = False
        db_table = 'berita'


class DjangoMigrations(models.Model):
    app = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    applied = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_migrations'


class Donatur(models.Model):
    email = models.ForeignKey('User', models.DO_NOTHING, db_column='email', primary_key=True)
    saldo = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'donatur'


class DonaturKegiatan(models.Model):
    donatur = models.ForeignKey(Donatur, models.DO_NOTHING, db_column='donatur', primary_key=True)
    kegiatan = models.ForeignKey('Kegiatan', models.DO_NOTHING, db_column='kegiatan')
    tanggal = models.DateField()
    nominal = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'donatur_kegiatan'
        unique_together = (('donatur', 'kegiatan'),)


class DonaturOrganisasi(models.Model):
    donatur = models.ForeignKey(Donatur, models.DO_NOTHING, db_column='donatur', primary_key=True)
    organisasi = models.ForeignKey('OrganisasiTerverifikasi', models.DO_NOTHING, db_column='organisasi')
    tanggal = models.DateField()
    nominal = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'donatur_organisasi'


class Kategori(models.Model):
    kode = models.CharField(primary_key=True, max_length=20)
    nama = models.CharField(max_length=50)

    class Meta:
        managed = False
        db_table = 'kategori'


class KategoriKegiatan(models.Model):
    kode_kegiatan = models.ForeignKey('Kegiatan', models.DO_NOTHING, db_column='kode_kegiatan', primary_key=True)
    kode_kategori = models.ForeignKey(Kategori, models.DO_NOTHING, db_column='kode_kategori')

    class Meta:
        managed = False
        db_table = 'kategori_kegiatan'
        unique_together = (('kode_kegiatan', 'kode_kategori'),)


class KeahlianRelawan(models.Model):
    email = models.ForeignKey('Relawan', models.DO_NOTHING, db_column='email', primary_key=True)
    keahlian = models.CharField(max_length=50)

    class Meta:
        managed = False
        db_table = 'keahlian_relawan'
        unique_together = (('email', 'keahlian'),)


class Kegiatan(models.Model):
    kode_unik = models.CharField(primary_key=True, max_length=20)
    organisasi_perancang = models.ForeignKey('OrganisasiTerverifikasi', models.DO_NOTHING, db_column='organisasi_perancang')
    judul = models.CharField(max_length=50)
    dana_dibutuhkan = models.IntegerField()
    tanggal_mulai = models.DateField()
    tanggal_selesai = models.DateField()
    dekskripsi = models.TextField()

    class Meta:
        managed = False
        db_table = 'kegiatan'


class LaporanKeuangan(models.Model):
    organisasi = models.ForeignKey('OrganisasiTerverifikasi', models.DO_NOTHING, db_column='organisasi', primary_key=True)
    tgl_dibuat = models.DateField()
    rincian_pemasukan = models.TextField()
    total_pemasukan = models.IntegerField()
    total_pengeluaran = models.IntegerField()
    is_disetujui = models.BooleanField()

    class Meta:
        managed = False
        db_table = 'laporan_keuangan'
        unique_together = (('organisasi', 'tgl_dibuat'),)


class Organisasi(models.Model):
    email_organisasi = models.CharField(primary_key=True, max_length=50)
    website = models.CharField(max_length=50)
    nama = models.CharField(max_length=50)
    provinsi = models.CharField(max_length=50)
    kabupaten_kota = models.CharField(max_length=50)
    kecamatan = models.CharField(max_length=50)
    keluarahan = models.CharField(max_length=50)
    kode_pos = models.CharField(max_length=50)
    status_verifikasi = models.CharField(max_length=50)

    class Meta:
        managed = False
        db_table = 'organisasi'


class OrganisasiTerverifikasi(models.Model):
    email_organisasi = models.ForeignKey(Organisasi, models.DO_NOTHING, db_column='email_organisasi', primary_key=True)
    nomor_registrasi = models.CharField(max_length=50)
    status_aktif = models.CharField(max_length=50)

    class Meta:
        managed = False
        db_table = 'organisasi_terverifikasi'


class PengurusOrganisasi(models.Model):
    email = models.ForeignKey('User', models.DO_NOTHING, db_column='email', primary_key=True)
    organisasi = models.ForeignKey(Organisasi, models.DO_NOTHING, db_column='organisasi')

    class Meta:
        managed = False
        db_table = 'pengurus_organisasi'


class PenilaianPerforma(models.Model):
    email_relawan = models.ForeignKey('Relawan', models.DO_NOTHING, db_column='email_relawan', primary_key=True)
    organisasi = models.ForeignKey(OrganisasiTerverifikasi, models.DO_NOTHING, db_column='organisasi')
    id = models.IntegerField()
    deskripsi = models.TextField()
    tgl_penilaian = models.DateField()
    nilai_skala = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'penilaian_performa'
        unique_together = (('email_relawan', 'organisasi', 'id'),)


class Relawan(models.Model):
    email = models.ForeignKey('User', models.DO_NOTHING, db_column='email', primary_key=True)
    no_hp = models.CharField(max_length=20)
    tanggal_lahir = models.DateField()

    class Meta:
        managed = False
        db_table = 'relawan'


class RelawanOrganisasi(models.Model):
    email_relawan = models.ForeignKey(Relawan, models.DO_NOTHING, db_column='email_relawan', primary_key=True)
    organisasi = models.ForeignKey(Organisasi, models.DO_NOTHING, db_column='organisasi')

    class Meta:
        managed = False
        db_table = 'relawan_organisasi'
        unique_together = (('email_relawan', 'organisasi'),)


class Reward(models.Model):
    kode_kegiatan = models.ForeignKey(Kegiatan, models.DO_NOTHING, db_column='kode_kegiatan', primary_key=True)
    barang_reward = models.CharField(max_length=50)
    harga_min = models.IntegerField()
    harga_max = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'reward'


class Sponsor(models.Model):
    email = models.ForeignKey('User', models.DO_NOTHING, db_column='email', primary_key=True)
    logo_sponsor = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'sponsor'


class SponsorOrganisasi(models.Model):
    sponsor = models.ForeignKey(Sponsor, models.DO_NOTHING, db_column='sponsor', primary_key=True)
    organisasi = models.ForeignKey(OrganisasiTerverifikasi, models.DO_NOTHING, db_column='organisasi')
    tanggal = models.DateField()
    nominal = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'sponsor_organisasi'
        unique_together = (('sponsor', 'organisasi'),)


class TujuanOrganisasi(models.Model):
    organisasi = models.ForeignKey(Organisasi, models.DO_NOTHING, db_column='organisasi', primary_key=True)
    tujuan = models.TextField()

    class Meta:
        managed = False
        db_table = 'tujuan_organisasi'
        unique_together = (('organisasi', 'tujuan'),)


class User(models.Model):
    email = models.CharField(primary_key=True, max_length=50)
    password = models.CharField(max_length=50)
    nama = models.CharField(max_length=100)
    alamat = models.TextField()

    class Meta:
        managed = False
        db_table = 'user'

login/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse

# Create your views here.
response = {}

def index(request):
    if 'email' in request.session :
            print('logged in')
            print('di login')
            response['login'] = True
            return HttpResponseRedirect(reverse('profil_user:index'))
    else :
            print('not logged in')
            response['login'] = False
            html = 'homepage.html'
            return render(request, html, response)

def login(request):
    if 'email' in request.session :
            print('logged in')
            response['login'] = True
            return HttpResponseRedirect(reverse('profil_user:index'))
    else :
            print('not logged in')
            response['login'] = False
            html = 'login.html'
            return render(request, html, response)

login/templates/homepage.html
{% load staticfiles %}
{% load static %}

<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css">
  <link rel="stylesheet" href="{% static 'theme.css'%}" type="text/css">
</head>
<body class="bg-secondary">
  <div class ="container">
      {% for message in messages %}
      <div class="alert {{ message.tags }} alert-dismissible" role="alert" id="django-messages">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close" style="margin-right: 15px;">
          <span aria-hidden="true">&times;</span>
        </button>
        {{ message }}
      </div>
      {% endfor %}
    </div>    
  <nav class="navbar navbar-expand-md bg-secondary navbar-dark">
    <a class="navbar-brand" href="#">
      <i class="fa d-inline fa-lg fa-cloud"></i>
      <b> SION</b>
    </a>
    <div class="container">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto"></ul>
        <form class="form-inline m-0">
          <input class="form-control mr-2" type="text" placeholder="Search">
          <button class="btn btn-success" type="submit">Search</button>
        </form>
      </div>
    </div>
    <a class="btn navbar-btn ml-2 text-white btn-secondary" href="login/">
      <i class="fa d-inline fa-lg fa-user-circle-o"></i> Sign in/Register</a>
  </nav>
  <div class="py-5 text-center filter-dark" style="background-image: url('https://imgur.com/a/R1wdlw6');background-position:left top;background-size:cover;">
    <div class="container py-5">
      <div class="row">
        <div class="col-md-12">
          <h1 class="display-3 mb-4 text-light text-center">
            <b>Sistem Informasi Organisasi Nirlaba</b>
          </h1>
          <p class="lead mb-5 text-left">Bergabunglah bersama SION dan menjadi bagian dari kebaikan. Daftar sebagai relawan, donatur, atau sponsor. Daftarkan pula organisasimu.</p>
        </div>
      </div>
    </div>
  </div>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>

</html>

login/templates/login.html
{% load staticfiles %}
{% load static %}

<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css">
  <link rel="stylesheet" href="{% static 'theme.css'%}" type="text/css">
</head>

<body class="bg-secondary">
  <div class ="container">
      {% for message in messages %}
      <div class="alert {{ message.tags }} alert-dismissible" role="alert" id="django-messages">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close" style="margin-right: 15px;">
          <span aria-hidden="true">&times;</span>
        </button>
        {{ message }}
      </div>
      {% endfor %}
    </div>      
  <nav class="navbar navbar-expand-md bg-secondary navbar-dark">
    <a class="navbar-brand" href="#">
      <i class="fa d-inline fa-lg fa-cloud"></i>
      <b> SION</b>
    </a>
    <div class="container">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto"></ul>
        <form class="form-inline m-0">
          <input class="form-control mr-2" type="text" placeholder="Search">
          <button class="btn btn-success" type="submit">Search</button>
        </form>
      </div>
    </div>
    <a class="btn navbar-btn ml-2 text-white btn-secondary">
      <i class="fa d-inline fa-lg fa-user-circle-o"></i> Sign in/Register</a>
  </nav>
  <div class="py-5">
    <div class="container">
      <div class="row">
        <div class="col-md-3"> </div>
        <div class="col-md-6">
          <div class="card text-white p-5 bg-secondary">
            <div class="card-body">
              <h1 class="mb-4">Sign in</h1>
              <form action="{% url 'login:auth_login' %}" method="POST">
                {% csrf_token %}
                <div class="form-group">
                  <label>Alamat email</label>
                  <input type="email" name="email" class="form-control" placeholder="Enter email"> </div>
                <div class="form-group">
                  <label>Password</label>
                  <input type="password" name="password" class="form-control" placeholder="Password"> </div>
                <button type="submit" class="btn btn-success">Login</button>
              </form>
            </div>
            <a class="btn btn-secondary" href="{% url 'register:index' %}">Belum punya akun? Daftar disini.</a>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  <pingendo onclick="window.open('https://pingendo.com/', '_blank')" style="cursor:pointer;position: fixed;bottom: 10px;right:10px;padding:4px;background-color: #00b0eb;border-radius: 8px; width:250px;display:flex;flex-direction:row;align-items:center;justify-content:center;font-size:14px;color:white">Made with Pingendo Free&nbsp;&nbsp;
    <img src="https://pingendo.com/site-assets/Pingendo_logo_big.png" class="d-block" alt="Pingendo logo" height="16">
  </pingendo>
</body>

</html>