TK_SION/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView
import login.urls as login
import profil_user.urls as profil_user
import registrasi.urls as registrasi
import profil_organisasi.urls as profil_organisasi

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include(login,namespace='login')),
    url(r'^profile/',include(profil_user,namespace='profil_user')),
    url(r'^register/',include(registrasi,namespace='register')),
	url(r'^profil_organisasi/',include(profil_organisasi,namespace='profil_organisasi')),
]

login/urls.py
from django.conf.urls import url
from .views import index, login
from .custom_auth import auth_login, auth_logout

urlpatterns = [
    url(r'^$',index,name='index'),
    url(r'^login/$',login,name='login'),
    url(r'^custom_auth/login/$',auth_login,name='auth_login'),
    url(r'^custom_auth/logout/$',auth_logout,name='auth_logout'),
]

profil_user/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
    url(r'^$',index,name='index')
]

profil_user/models.py
from django.db import models

# Create your models here.

profil_user/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from login.db_helper import KoneksiDb

# Create your views here.
response = {}

def index(request):
        if 'email' in request.session :
                print('logged in')
                print('di profil')
                response['login'] = True

                conn = KoneksiDb()
                conn.cursor.execute("select * from sion.user where email='"+request.session['email']+"';")
                row = conn.cursor.fetchone()
                response['email'] = row[0]
                response['nama'] = row[2]
                response['alamat'] = row[3]
                response['role'] = request.session['role']
                html = 'profil_user.html'
                return render(request, html, response)

        else :
                print('not logged in')
                response['login'] = False
                return HttpResponseRedirect(reverse('login:index'))

profil_user/templates/profil_user.html
{% load staticfiles %}
{% load static %}

<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css">
  <link rel="stylesheet" href="{% static 'theme.css'%}" type="text/css">
</head>

<body class="bg-secondary">
    <div class ="container">
        {% for message in messages %}
        <div class="alert {{ message.tags }} alert-dismissible" role="alert" id="django-messages">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close" style="margin-right: 15px;">
            <span aria-hidden="true">&times;</span>
          </button>
          {{ message }}
        </div>
        {% endfor %}
      </div> 
  <nav class="navbar navbar-expand-md bg-secondary navbar-dark">
    <a class="navbar-brand" href="#">
      <i class="fa d-inline fa-lg fa-cloud"></i>
      <b> SION</b>
    </a>
    <div class="container">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="#">Organisasi</a>
          </li>
          {% if role == 'donatur' or role == 'sponsor' or role == 'relawan' %}
            <li class="nav-item">
              <a class="nav-link" href="#">Donasi ke Organisasi</a>
            </li>
          {% endif %}
          {% if role == 'donatur' or role == 'relawan' %}
          <li class="nav-item">
            <a class="nav-link" href="#">Donasi ke Organisasi</a>
          </li>
          {% endif %}
          {% if role == 'pengurus_organisasi' %}
          <li class="nav-item">
            <a class="nav-link" href="#">Buat Kegiatan</a>
          </li>
          <li class="nav-item">
              <a class="nav-link" href="#">Lihat Kegiatan</a>
            </li>
          {% endif %}
        </ul>
        <form class="form-inline m-0">
          <input class="form-control mr-2" type="text" placeholder="Search">
          <button class="btn btn-success" type="submit">Search</button>
        </form>
      </div>
    </div>
    <a class="btn navbar-btn ml-2 text-white btn-secondary">
      <i class="fa d-inline fa-lg fa-user-circle-o"></i> Halo, {{ nama }}</a>
    <a class="btn navbar-btn ml-2 text-white btn-danger" href="{% url 'login:auth_logout' %}">Log Out</a>
  </nav>
  <div class="py-5 text-white bg-secondary">
    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <img src="https://pingendo.github.io/templates/sections/assets/gallery_restaurant_1.jpg" atl="first slide" class="d-block img-fluid w-100">
          <p class="lead">Ini adalah contoh sedikit Bio dari profil {{ nama }}.</p>
        </div>
        <div class="col-md-6">
          <h1 class="">
            <b> {{ nama }}</b>
          </h1>
          <div class="col-md-6">
            <ul class="">
              <li>
                <b>Tipe User</b>
                <br>&nbsp; &nbsp; &nbsp; &nbsp;{{ role }}</li>
              <li>
                <b>Email</b>
                <br>&nbsp; &nbsp; &nbsp; &nbsp;{{ email }}</li>
              <li>
                <b>Alamat</b>
                <br>&nbsp; &nbsp; &nbsp; &nbsp;{{ alamat }}</li>
            </ul>
          </div>
          <div class="col-md-12">
            <ul class=""></ul>
            {% if "donatur" == role %}
              <p class="">
                <b>Saldo saat ini: Rp1.500.000,-</b>
              </p>
            {% endif %}

            {% if "sponsor" == role %}
              <p class="">
                <b>Saldo saat ini: Rp1.500.000,-</b>
              </p>
            {% endif %}

          </div>
        </div>
      </div>
    </div>
  </div>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>

</html>